package com.hms_networks.americas.sc.extensions.time;

/**
 * Class of constants for the HMS MU Americas Solution Center time library for Ewon Flexy devices.
 *
 * @since 1.0.0
 * @author HMS Networks, MU Americas Solution Center
 */
public class TimeLibConstants {

  /** Date format generated by the local time offset HTML file in result files. */
  public static final String TIME_OFFSET_DATE_FORMAT = "dd/MM/yyyy HH:mm:ss";

  /** Folder where time offset files should be stored on the filesystem. */
  public static final String TIME_OFFSET_DIRECTORY_PATH = "/usr/TimeOffset/";

  /** Name of the file which stores the exported local time result. */
  public static final String TIME_OFFSET_LOCAL_TIME_FILE_NAME = "ExportedLocalTimeValue.txt";

  /**
   * The export block descriptor value prefix (file name is appended) used to retrieve the local
   * time.
   */
  public static final String TIME_OFFSET_LOCAL_TIME_EBD_PREFIX = "$dtSE$se\"Time$\"$ftT$fn";
}
